---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Red Hat based OS update
      yum: >
        update_cache=yes
        name=*
        state=latest
        update_cache=yes
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    - name: Debian based OS update
      apt: >
        update_cache=yes
        cache_valid_time=1200
        upgrade=dist
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'


    - name: Install nginx repository (Red Hat based OS only)
      yum: >
        name=epel-release
        state=latest
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    - name: Install nginx - Red Hat based OS
      yum: >
         name=nginx
         state=latest
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    - name: Start nginx service (Red Hat based OS only)
      service:
        name: nginx
        state: started
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'


    - name: Install nginx - Debian based OS
      apt: >
         name=nginx
         state=latest
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'
