//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueGames.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Genre { get; set; }
        public string Developer { get; set; }
        public string Platform { get; set; }
        public Nullable<int> YearLaunch { get; set; }
    }
}
